### ISSUE TITLE
Plotter does not start with space in windows user name

### ISSUE THREAD

**Issue by SabrCat** [yhur/arduplot#20]
It's old tech debt curse that has been following me around for years. Unfortunately, my windows user name is ``HB Stratos`` with a space in it. 

This seems to be causing issues here, trying to monitor with the plotter filter defined causes this error:
```
Wrote 341200 bytes (181073 compressed) at 0x00010000 in 4.7 seconds (effective 581.3 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
--- serial_plotter is starting
  File "C:\Users\HB", line 1
    [982C:9868][2024-08-08T21:31:43]i001: Burn v3.10.4.4718, Windows v10.0 (Build 19045: Service Pack 0), path: C:\Windows\Temp\{B2EBD470-12BE-4B6E-BB6F-2AA5B069BD36}\.cr\VC_redist.x64.exe
       ^
SyntaxError: invalid decimal literal

Please build project in debug configuration to get more details about an exception.
See https://docs.platformio.org/page/projectconf/build_configurations.html
```

It seems like some part of the software is trying to read from a file named HB, which does exist, but other programs which do not like the space in my path end up writing to it. 

Other PIO filters such as ``esp32_exception_decoder`` or ``printable`` work fine. 

I did also test with built mode debug enabled, and it changed nothing.

**Comment by yhur** [comment]
This is for Windows only problem and happened due to this line.

```cmd
python %~dp0\arduplot %*
```
And it is fixed by
```cmd
python "%~dp0\arduplot" %*
```

**Comment by SabrCat** [comment]
Hi there! This has changed the error I am seeing, but unfortunately I am still seeing an error:

```
Writing at 0x0006456a... (92 %)
Writing at 0x00069e16... (100 %)
Wrote 376528 bytes (202881 compressed) at 0x00010000 in 5.2 seconds (effective 579.1 kbit/s)...
Hash of data verified.

Leaving...
Hard resetting via RTS pin...
--- serial_plotter is starting

Please build project in debug configuration to get more details about an exception.
See https://docs.platformio.org/page/projectconf/build_configurations.html


--- Terminal on COM5 | 115200 8-N-1
--- Available filters and text transformations: colorize, debug, default, direct, esp32_exception_decoder, hexlify, log2file, nocontrol, plotter, printable, send_on_enter, time
--- More details at https://bit.ly/pio-monitor-filters
--- Quit: Ctrl+C | Menu: Ctrl+T | Help: Ctrl+T followed by Ctrl+H
C:\Users\HB Stratos\.platformio\penv\Lib\site-packages\arduplot\plotserialdata.py:192: UserWarning: FigureCanvasAgg is non-interactive, and thus cannot be shown
  plt.show()
OOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:2
load:0x3fff0030,len:1288
load:0x40078000,len:13856
load:0x40080400,len:4
ho 8 tail 4 room 4
load:0x40080404,len:3048
entry 0x40080590
[   363][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   381][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   399][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   416][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   432][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   449][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   466][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   483][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   500][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   517][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   534][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   551][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   569][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   586][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   602][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   619][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   636][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
[   653][E][Wire.cpp:515] requestFrom(): i2cWriteReadNonStop returned Error -1
IMU initialized successfully!
Initializing EarController...
Configuring driver...
Configuring PID...
C:\Users\HB Stratos\.platformio\penv\Lib\site-packages\matplotlib\animation.py:908: UserWarning: Animation was deleted without rendering anything. This is most likely not intended. To prevent deletion, assign the Animation to a variable, e.g. `anim`, that exists until you output the Animation using `plt.show()` or `anim.save()`.
  warnings.warn(

 *  The terminal process "C:\Users\HB Stratos\.platformio\penv\Scripts\platformio.exe 'run', '--target', 'upload', '--target', 'monitor', '--environment', 'esp32dev'" terminated with exit code: 2. 
 *  Terminal will be reused by tasks, press any key to close it. 
```

I should also note that during install time of arduplot, I got several warnings that the scripts folder was not in PATH. I am not sure if this is relevant here.

**Comment by iot101student** [comment]
Is pyqt5 installed on your Windows? Install it if not. The  PlatformIO used to install it, but newer version of PIO doesn’t.
